spring:
  config:
    activate:
      on-profile: server
  webclient:
    baseUrl: http://localhost:58082 #External API base URL
    endpointSchedule: /api/v1/sandbox/asset-missions #Endpoint for scheduling
    max-in-memory-size: 1024KB
    read-timeout: 10s
    write-timeout: 10s
    connect-timeout: 10s

websocket: #Configure WebSocket connection to external service
  protocol: ws
  path: /test 
  port: 8001
  host: localhost
  connectionTimeout: 5
  isEnabled: true

server:  #Own server configuration
  port: 8001